#ifndef RENDERER_EVENT_HPP
#define RENDERER_EVENT_HPP

namespace gfx {
    enum RENDERER_EVENT {
        RENDERER_EVENT_NONE,
        RENDERER_EVENT_SHOWN,
        RENDERER_EVENT_HIDDEN,
        RENDERER_EVENT_EXPOSED,
        RENDERER_EVENT_MOVED,
        RENDERER_EVENT_RESIZED,
        RENDERER_EVENT_MINIMIZED,
        RENDERER_EVENT_MAXIMIZED,
        RENDERER_EVENT_RESTORED,
        RENDERER_EVENT_ENTER,
        RENDERER_EVENT_LEAVE,
        RENDERER_EVENT_FOCUS_GAINED,
        RENDERER_EVENT_FOCUS_LOST,
        RENDERER_EVENT_CLOSE,
    };
}

#endif //RENDERER_EVENT_HPP
