#ifndef WINDOW_EVENT_HPP
#define WINDOW_EVENT_HPP

namespace gfx {
    enum WINDOW_EVENT {
        WINDOW_EVENT_SHOWN,
        WINDOW_EVENT_HIDDEN,
        WINDOW_EVENT_EXPOSED,
        WINDOW_EVENT_MOVED,
        WINDOW_EVENT_RESIZED,
        WINDOW_EVENT_MINIMIZED,
        WINDOW_EVENT_MAXIMIZED,
        WINDOW_EVENT_RESTORED,
        WINDOW_EVENT_ENTER,
        WINDOW_EVENT_LEAVE,
        WINDOW_EVENT_FOCUS_GAIND,
        WINDOW_EVENT_FOCUS_LOST,
        WINDOW_EVENT_CLOSE
    };
}

#endif //WINDOW_EVENT_HPP
